---
title: Nanny Match
timezone: Australia/Melbourne
permalink: pretty
exclude:
- Gruntfile.js
- webpack.config.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: assets/styles/
  style: compressed
phone: 0406 262 869
email: ruby@nannymatch.co
address_line_1: 9/41 Hanover St
address_line_2: Fitzroy 3065
address_line_3: Melbourne, VIC
google_analytics: UA-72697217-1
