---
title: Nanny Match Melbourne
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    author: ruby
    target: parents
permalink: pretty
exclude:
- Gruntfile.js
- webpack.config.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: assets/styles/
  style: compressed
phone: "(03) 9088 2062"
phone_local: 61390882062
email: ruby@nannymatch.com.au
address_line_1: 9/41 Hanover St
address_line_2: Fitzroy
address_line_3: Melbourne VIC 3065
google_analytics: UA-72697217-1
description: Find a nanny in Melbourne
url: http://nannymatch.com.au
authors:
  ruby:
    name: Ruby Brown
    avatar: "/uploads/ruby.jpg"
    email: ruby@nannymatch.com.au
social:
  name: Nanny Match Melbourne
  links:
  - https://www.facebook.com/NannyMatchMelbourne/
  - https://plus.google.com/+Nannymatch
  - https://www.instagram.com/nannymatch
