---
title: Nanny Match Melbourne
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    author: ruby
    target: parents
permalink: pretty
exclude:
- Gruntfile.js
- webpack.config.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: assets/styles/
  style: compressed
phone: 0406 262 869
email: ruby@nannymatch.com.au
address_line_1: 9/41 Hanover St
address_line_2: Fitzroy 3065
address_line_3: Melbourne, VIC
google_analytics: UA-72697217-1
description: Find a nanny in Melbourne
url: http://nannymatch.com.au
authors:
  ruby:
    name: Ruby Brown
    avatar: "/uploads/ruby.jpg"
    email: ruby@nannymatch.com.au
